---
title: "CodeBook"
author: "Ahmed Abdel Gawad"
date: "12/31/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary:

This is a CodeBook for the tidyset data that has been submitted for the "Getting and Cleaning Data Course Project". 

## Original Data Set Information:

The data for the project was obtained from [here] (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

Check the **README.Rmd** file for further details about the original dataset.

## Work done to tidy the data:

Several steps were completed to arrive at the tidyset. This involved: 

1. Merging different files from the original dataset
2. Cleaning variable names to make them more descriptive
3. Summarizing the data by the average of each variable for each activity and each subject

Check the **run_analysis.R** file for further details about the steps undertaken to arrive at the tidyset from the original dataset. 

## Features Information:

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals timeacceration-XYZ and timegyro-XYZ. These time domain signals were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (timebodyacceration-XYZ and timegravityacceleration-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (timebodyaccelerationjerk-XYZ and timebodygyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (timebodyacclerationmagnitude, timegravityaccelrationmagnitude, timebodyaccelerationjerkmagnitude, timebodygyromagnitude, timebodygyrojerkmagnitude). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing frequencybodyacceleration-XYZ, frequencybodyaccelerationjerk-XYZ, frequencybodygyro-XYZ, frequencybodyaccelerationjerkmagnitude, frequencybodygyromagnitude, frequencybodygyrojerkmagnitude. 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

timebodyacceleration-XYZ

timegravityacceleration-XYZ

timebodyaccelerationjerk-XYZ

timebodygyro-XYZ

timebodygyrojerk-XYZ

timebodyaccelerationmagnitude

timegravityaccelerationmagnitude

timebodyaccelerationjerkmagnitude

timebodygyromagnitude

timebodygyrojerkmagnitude

frequencybodyacceleration-XYZ

frequencybodyaccelerationjerk-XYZ

frequencybodygyro-XYZ

frequencybodyaccelerationmagnitude

frequencybodyaccelerationjerkmagnitude

frequencybodygyromagnitude

frequencybodygyrojerkmagnitude

The set of variables that were estimated from these signals are: 

mean: Mean value

standarddeviation: Standard deviation

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravitymean

timebodyaccelerationmean

timebodyaccelerationjerkmean

timebodygyromean

timebodygyrojerkmean
